devices:
  - hostname: Vislabs-iPhone.local
    attached_name: iPhone Vislab
    script: "scripts/example.py"
  - hostname: Signlabs-iPhone.local
    attached_name: iPhone SignLab
    script: "scripts/example.py"
  - hostname: ShogunLive.local
    attached_name: Shogun Live API
    script: "scripts/example.py"
  - hostname: OBS
    attached_name: OBS
    script: "scripts/OBSinterface.py"

server:
  ws_port: 8766
  ws_addr: "localhost"
  http_port: 8000
  http_addr: "localhost"

listen_server:
  module: unrealServer
  entrypoint: receive_messages
  uri: wss://signcollect.nl/unrealServer/
